### ISSUE TITLE
non effettua l'accesso 

### ISSUE THREAD

**Issue by Delineat** [matteopillon/Delineat.Assistant#13]
![image](https://user-images.githubusercontent.com/84308231/119217878-7f3a5480-badd-11eb-9d56-b5b679a388c6.png)

**Comment by Delineat** [comment]
![image](https://user-images.githubusercontent.com/84308231/119217940-e9eb9000-badd-11eb-9e04-e9377abf62d6.png)

**Comment by matteopillon** [comment]
Sistemata la gestione dei certificati
