### ISSUE TITLE
estrazione registro ore

### ISSUE THREAD

**Issue by Delineat** [matteopillon/Delineat.Assistant#7]
dopo il primo periodo di rodaggio inseriremo le ore solo qui (ora facciamo le registrazione doppia, qui e in access) 
è possibile decidere di esportare le registrazioni da una certa data per riaggiornare i valori in access?
questo vale per le ore registrate e per le nuove commesse

**Comment by matteopillon** [comment]
Purtroppo il formato è diverso, non si riesce ad importare
