### ISSUE TITLE
codici aggiuntivi

### ISSUE THREAD

**Issue by Delineat** [matteopillon/Delineat.Assistant#9]
![image](https://user-images.githubusercontent.com/84308231/119159785-e31a3a00-ba57-11eb-97c6-8a90028802e9.png)

Se aggiungo un codice a una commessa già esistente, quel codice me lo riconosce solo nella sessione attiva, appena chiudo e riapro l’assistant non mi trova più quel codice

![image](https://user-images.githubusercontent.com/84308231/119159799-e6adc100-ba57-11eb-9fc2-8b61433a56b5.png)

**Comment by matteopillon** [comment]
Non riesco a riprodurre il caso

**Comment by Delineat** [comment]
![image](https://user-images.githubusercontent.com/84308231/120677514-71021600-c497-11eb-85c6-63769e43671c.png)
![image](https://user-images.githubusercontent.com/84308231/120677573-81b28c00-c497-11eb-9b5a-75314707916d.png)
non so se il problema è che non aggiunge realmente il codice, se faccio salva mi da questo, poi devo fare annulla
![image](https://user-images.githubusercontent.com/84308231/120677679-a0b11e00-c497-11eb-953c-c199f30fb231.png)
![image](https://user-images.githubusercontent.com/84308231/120677723-adce0d00-c497-11eb-874e-3f1a20df81c9.png)
ora su questo PC me la trova, sugli altri pc e dopo il riavvio dell'assistant invece non trova niente
![image](https://user-images.githubusercontent.com/84308231/120677901-d9e98e00-c497-11eb-8186-2e65896e9512.png)

**Comment by matteopillon** [comment]
Ho provato diverse volte e non mi ha dato problemi salvando sempre le modifiche, da te è sistematico l'errore?

**Comment by matteopillon** [comment]
La cache viene svuotata ogni 5 minuti
